// Generated by scripts/sync-shared.mjs from shared/client/settings/market-tab.ts. Do not edit this copy; edit the shared source and run "node scripts/sync-shared.mjs".
/**
 * DSH Market tab seat — the family-shared contract for the single first-level
 * settings section `dsh-market` (the hub): it declares the `dsh-market.tab`
 * child slot, and the Skin Center / Pet / Community Plugins / Store cards
 * register into it as tab panels.
 *
 * Two-seat discipline (the family hub pattern, cf. web-ui.plugin.item):
 *   - With the hub installed, a card registers into `dsh-market.tab` (tab
 *     mode) and is rendered as one tab panel by the hub.
 *   - Standalone (hub absent), the same card registers its own first-level
 *     `settings.section` entry (fallback mode) so the package keeps its
 *     standalone settings surface.
 * A card applies BOTH waits: the `settings.section` fallback is skipped once
 * the hub's tab declaration is live, and a late hub takeover disposes the
 * fallback entry, so the two modes never render together regardless of boot
 * order.
 *
 * Tab panels receive the same owner share the hub passes down: `close`
 * (drill-out of the settings panel), matching `settings.section`'s owner
 * share, so the same card component serves both seats.
 */

import type { ClientContext } from '@deepseek-ai/dsh-client-runtime/client'
import type {} from '@deepseek-ai/dsh-client-ui-slots'

declare module '@deepseek-ai/dsh-client-ui-slots' {
  interface SlotMap {
    /**
     * The child slot the DSH Market hub declares; category cards register
     * into it instead of the top-level `settings.section` list. Spelled here
     * with the same shape in every consumer via this shared copy.
     */
    'dsh-market.tab': { kind: 'list'; scope: 'root'; owner: MarketTabOwnerProps }
  }
}

/** Owner share of a DSH Market tab panel (the hub passes the section's close). */
export interface MarketTabOwnerProps {
  /** Close the settings panel (the hub owns the open state). */
  close: () => void
}

/** The child slot key the DSH Market hub declares and category cards register into. */
export const MARKET_TAB_KEY = 'dsh-market.tab' as const

/** One tab listed by the hub's tab bar. */
export interface MarketTabRecord {
  /** The registered entry id (dispatch key for `only` filtering). */
  id: string
  /** The entry's resolved label (follows the active locale). */
  label: string
}

/** The card's two seat registrations and its shared-resource release. */
export interface MarketTabSeat {
  /** Register the hub tab entry (caller-typed register into MARKET_TAB_KEY). */
  registerTab(): () => void
  /** Register the standalone settings.section fallback entry. */
  registerSection(): () => void
  /** Release whatever the live seat owns (card controller disposal). */
  release(): void
}

/**
 * Install the two-seat registration machine for one category card. The card
 * applies waits on BOTH seats: the section fallback is skipped while the
 * hub's tab declaration is live, and a late hub takeover unregisters the
 * fallback entry (without releasing shared resources), so the two modes never
 * render together regardless of boot order. `release` fires exactly once,
 * when the LIVE seat dies.
 * @param ctx - client root context (slots service).
 * @param seat - the card's registrations and release hook.
 * @returns an idempotent disposer for both waits (the waits are also collected
 * by the caller's fiber, like every slots.inject effect).
 */
export function installMarketTabSeat(ctx: ClientContext, seat: MarketTabSeat): () => void {
  let live: 'tab' | 'section' | null = null
  let fallbackEntry: (() => void) | null = null
  const disposeTabWait = ctx.slots.inject(MARKET_TAB_KEY, () => {
    live = 'tab'
    const unregister = seat.registerTab()
    if (fallbackEntry) {
      fallbackEntry()
      fallbackEntry = null
    }
    return () => {
      if (live === 'tab') {
        live = null
        seat.release()
      }
      unregister()
    }
  })
  const disposeSectionWait = ctx.slots.inject('settings.section', () => {
    if (live === 'tab') return () => {}
    live = 'section'
    fallbackEntry = seat.registerSection()
    return () => {
      if (live === 'section') {
        live = null
        seat.release()
      }
      fallbackEntry = null
    }
  })
  return () => {
    disposeTabWait()
    disposeSectionWait()
  }
}
